<a href="https://colab.research.google.com/github/atpathak/ML-code-templates_2026/blob/main/Kernel_PCA_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('Wine.csv')
dataset.head(10)

Alcohol  Malic_Acid   Ash  ...  OD280  Proline  Customer_Segment
0    14.23        1.71  2.43  ...   3.92     1065                 1
1    13.20        1.78  2.14  ...   3.40     1050                 1
2    13.16        2.36  2.67  ...   3.17     1185                 1
3    14.37        1.95  2.50  ...   3.45     1480                 1
4    13.24        2.59  2.87  ...   2.93      735                 1
5    14.20        1.76  2.45  ...   2.85     1450                 1
6    14.39        1.87  2.45  ...   3.58     1290                 1
7    14.06        2.15  2.61  ...   3.58     1295                 1
8    14.83        1.64  2.17  ...   2.85     1045                 1
9    13.86        1.35  2.27  ...   3.55     1045                 1

[10 rows x 14 columns]

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Applying Kernel PCA**

In [6]:
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(n_components = 2, kernel = 'rbf')
X_train = kpca.fit_transform(X_train)
X_test = kpca.transform(X_test)

In [7]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [8]:
y_pred = classifier.predict(X_test)
np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)

array([[1, 1],
       [3, 3],
       [2, 2],
       [1, 1],
       [2, 2],
       [2, 2],
       [1, 1],
       [3, 3],
       [2, 2],
       [2, 2],
       [3, 3],
       [3, 3],
       [1, 1],
       [2, 2],
       [3, 3],
       [2, 2],
       [1, 1],
       [1, 1],
       [2, 2],
       [1, 1],
       [2, 2],
       [1, 1],
       [1, 1],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [3, 3],
       [1, 1],
       [1, 1],
       [2, 2],
       [1, 1],
       [1, 1],
       [1, 1]])

In [9]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("confusion_matrix: \n", cm)
accuracy_score(y_test, y_pred)

confusion_matrix: 
 [[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]


1.0